; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nucleo_g474re]
platform = ststm32
board = nucleo_g474re
framework = mbed
monitor_speed = 115200
upload_protocol = stlink
debug_tool = stlink

; Подключаем автогенерируемый файл (как .pri в Qt)
extra_scripts = pre:auto_paths.py

;lib_deps = lvgl/lvgl@~8.4.0
; Явно указываем Mbed OS 6+
; platform_packages =
;    framework-mbed @ 6.18.0

; Указываем стандарт C++17
; cxx_standard = 17

;extra_scripts = force_cpp.py

build_flags = 
    -std=gnu++17
    -DMBED_EXCLUDE_TARGET_FILES_FROM_TESTS
    -DUNITTESTS=0
    -Iinclude
    -DPIO_FRAMEWORK_MBED_RTOS_PRESENT
    -Wall
    -Wextra
    -Wno-unused-parameter

build_src_filter = +<*> -<**/TEMP> -<**/temp> -<**/Temp> -<**/TEST> -<**/test> -<**/Test>

debug_init_break = tbreak main
targets = upload

;lib_ldf_mode = deep+
